name: Create Feature or Bug Branch from Approved Issues

on:
  issues:
    types: [labeled]
  workflow_dispatch: # Allow Github Actions to run this manually 

jobs:
  create-branch:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'approved'

    steps:
      - name: Check for Bug or Feature Label
        id: check_label
        run: |
          LABELS_JSON='${{ toJson(github.event.issue.labels) }}'
          if echo "$LABELS_JSON" | grep -q '"bug"'; then
            echo "BRANCH_PREFIX=bugs/bug" >> $GITHUB_ENV
          elif echo "$LABELS_JSON" | grep -q '"feature"'; then
            echo "BRANCH_PREFIX=features/feature" >> $GITHUB_ENV
          else
            echo "❌ Issue is missing 'bug' or 'feature' label. Exiting."
            exit 1
          fi

      - name: Checkout latest dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Generate Branch Name
        id: generate_branch
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"

          # Convert issue title into a branch-safe format
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-*//;s/-*$//')
          BRANCH_NAME="${BRANCH_PREFIX}-${SAFE_TITLE}-${ISSUE_NUMBER}"

          echo "Branch name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create and Push Branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

      - name: Comment on Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          BRANCH_NAME="${{ env.BRANCH_NAME }}"

          gh issue comment "$ISSUE_NUMBER" --body "✅ A new branch [$BRANCH_NAME](https://github.com/${{ github.repository }}/tree/$BRANCH_NAME) has been created from the latest 'dev' branch."
