name: Create Bug Branch from Approved Issue

on:
  issues:
    types: [labeled]
  workflow_dispatch: # Allow Github Actions to run this manually 

jobs:
  create-bug-branch:
    name: Create Bug Branch
    runs-on: ubuntu-latest
    if: github.event.label.name == 'approved' && contains(github.event.issue.labels.*.name, 'bug')
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set Branch Prefix
        run: echo "BRANCH_PREFIX=bugs/bug" >> $GITHUB_ENV

      - name: Generate Branch Name
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          # Remove [BUG]
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | sed -E 's/^\[BUG\]\s*//')
          # Make title branch friendly
          SAFE_TITLE=$(echo "$SAFE_TITLE" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-*//;s/-*$//')
          BRANCH_NAME="${BRANCH_PREFIX}-${SAFE_TITLE}-${ISSUE_NUMBER}"
          echo "Branch name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create and Push Branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH_NAME"
          git push https://x-access-token:${GH_TOKEN}@github.com/alvyOG/mythic-plus-coach.git "$BRANCH_NAME"

      - name: Comment on Issue
        run: |
          gh issue comment "${{ github.event.issue.number }}" --body "✅ A new branch [$BRANCH_NAME](https://github.com/${{ github.repository }}/tree/$BRANCH_NAME) has been created."
